/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as NotebookUrlImport } from "./routes/$notebookUrl";
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const NotebookUrlRoute = NotebookUrlImport.update({
  path: "/$notebookUrl",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/$notebookUrl": {
      id: "/$notebookUrl";
      path: "/$notebookUrl";
      fullPath: "/$notebookUrl";
      preLoaderRoute: typeof NotebookUrlImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$notebookUrl": typeof NotebookUrlRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$notebookUrl": typeof NotebookUrlRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/$notebookUrl": typeof NotebookUrlRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$notebookUrl";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$notebookUrl";
  id: "__root__" | "/" | "/$notebookUrl";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  NotebookUrlRoute: typeof NotebookUrlRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotebookUrlRoute: NotebookUrlRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$notebookUrl"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$notebookUrl": {
      "filePath": "$notebookUrl.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
